#!/usr/bin/env python3
"""Generate Search-R1 cold-start traces with Qwen3.5-27B and Lucene BM25.

This is deliberately an online tool-use loop: every ``<search>`` emitted by
the teacher is executed against the local Wikipedia Lucene index and the
returned passages are fed back as ``<information>``.  The output is raw JSONL;
run ``validate_teacher_traces.py`` before using it for SFT.
"""
from __future__ import annotations

import argparse
import json
import linecache
import random
import re
import string
from pathlib import Path

import pyarrow.parquet as pq
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from trace_validation import validate_tool_progress


ANSWER_RE = re.compile(r"<answer>\s*(.*?)\s*</answer>", re.I | re.S)


def normalize(text: str) -> str:
    # Match Search-R1's QA EM normalization (case/punctuation/articles do not
    # affect correctness, while the answer itself still must be generated by
    # the teacher and appear inside an <answer> block).
    text = text.lower()
    text = "".join(ch for ch in text if ch not in set(string.punctuation))
    text = re.sub(r"\b(a|an|the)\b", " ", text)
    return " ".join(text.split())


def normalize_segment(text: str) -> str:
    """Restore the implicit Qwen thinking opener used by chat templates."""
    # Models occasionally mention tag names in backticks while reasoning;
    # those are prose, not structural delimiters, and must not confuse the
    # strict Search-R1 sequence parser.
    text = re.sub(
        r"`(</?(?:think|search|information|answer)>)`",
        lambda match: match.group(1).replace("<", "[").replace(">", "]"),
        text,
    )
    if "</think>" in text and "<think>" not in text:
        return "<think>" + text
    return text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--teacher", default="models/Qwen3.5-27B")
    ap.add_argument("--input", default="data/processed/nq_hotpotqa_train/train.parquet")
    ap.add_argument("--index", default="data/index/bm25")
    ap.add_argument("--corpus", default="data/corpus/wiki-18.jsonl", help="JSONL corpus used when Lucene stores no raw documents")
    ap.add_argument("--output", default="data/processed/teacher_traces_qwen35_27b.jsonl")
    ap.add_argument("--count", type=int, default=20000, help="Generate extra rows for filtering; validator keeps 15k+eval.")
    ap.add_argument("--topk", type=int, default=3)
    ap.add_argument("--max-rounds", type=int, default=8)
    ap.add_argument("--max-searches", type=int, default=100, help="Optional safety cap; normal termination is controlled by --max-rounds.")
    ap.add_argument("--max-tokens", type=int, default=768)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--top-p", type=float, default=0.9)
    ap.add_argument("--stop-at-search", action="store_true", help="Stop each decode at </search> so tool results are injected immediately.")
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--debug-output", default=None, help="Optional JSONL for rejected/generated states during smoke tests.")
    ap.add_argument("--resume", action="store_true", help="Append to an existing output and skip row ids already written.")
    ap.add_argument("--shard-index", type=int, default=0, help="Zero-based shard id for parallel generation.")
    ap.add_argument("--num-shards", type=int, default=1, help="Number of disjoint row shards for parallel generation.")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--gpu-memory-utilization", type=float, default=0.90)
    ap.add_argument("--use-vllm-compile", action="store_true", help="Try vLLM torch.compile; disabled by default because this environment has a known compile incompatibility.")
    ap.add_argument("--tensor-parallel-size", type=int, default=1)
    args = ap.parse_args()
    if args.num_shards < 1 or not 0 <= args.shard_index < args.num_shards:
        raise SystemExit("--shard-index must be in [0, --num-shards)")

    from pyserini.search.lucene import LuceneSearcher
    from verl.utils.reward_score.qa_em_format import is_valid_sequence

    rows = pq.read_table(args.input, columns=["question", "golden_answers", "data_source"]).to_pylist()
    rng = random.Random(args.seed)
    rng.shuffle(rows)
    rows = rows[: args.count]
    if len(rows) < args.count:
        raise SystemExit(f"Input has only {len(rows)} rows, cannot generate {args.count}")
    if args.num_shards > 1:
        rows = rows[args.shard_index :: args.num_shards]
    searcher = LuceneSearcher(args.index)

    def hit_contents(hit) -> str:
        """Return passage text, falling back to the line-aligned JSONL corpus.

        The production BM25 index intentionally omits stored raw fields to
        keep the index smaller.  Pyserini's hit docids are the original
        JSONL line ids, so reading that line restores the exact passage.
        """
        raw = searcher.doc(hit.docid).raw()
        if raw:
            try:
                value = json.loads(raw)
                return str(value.get("contents", value))
            except (json.JSONDecodeError, TypeError, AttributeError):
                return str(raw)
        try:
            line_no = int(hit.docid) + 1
        except (TypeError, ValueError):
            return ""
        line = linecache.getline(args.corpus, line_no)
        if not line:
            return ""
        try:
            return str(json.loads(line).get("contents", ""))
        except (json.JSONDecodeError, TypeError, AttributeError):
            return ""

    tokenizer = AutoTokenizer.from_pretrained(args.teacher, trust_remote_code=True)
    llm = LLM(
        model=args.teacher,
        trust_remote_code=True,
        dtype="bfloat16",
        tensor_parallel_size=args.tensor_parallel_size,
        max_model_len=4096,
        gpu_memory_utilization=args.gpu_memory_utilization,
        enforce_eager=not args.use_vllm_compile,
        # Avoid the known FlashInfer GDN PTX issue on this CUDA toolchain.
        gdn_prefill_backend="triton",
    )
    sampling = SamplingParams(
        temperature=args.temperature,
        top_p=args.top_p,
        max_tokens=args.max_tokens,
        stop=["</search>"] if args.stop_at_search else None,
        include_stop_str_in_output=args.stop_at_search,
    )
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    completed_questions = set()
    if args.resume and out_path.exists():
        with out_path.open(encoding="utf-8") as existing:
            for line in existing:
                try:
                    question = str(json.loads(line).get("question", "")).strip()
                    if question:
                        completed_questions.add(question)
                except (ValueError, TypeError, json.JSONDecodeError):
                    continue
        rows = [row for row in rows if str(row.get("question", "")).strip() not in completed_questions]
        print(json.dumps({"resume_skipped": len(completed_questions), "remaining": len(rows)}), flush=True)
    written = 0
    debug = Path(args.debug_output).open("w", encoding="utf-8") if args.debug_output else None
    mode = "a" if args.resume else "w"
    with out_path.open(mode, encoding="utf-8") as out:
        for start in range(0, len(rows), args.batch_size):
            states = []
            for row_no, row in enumerate(rows[start : start + args.batch_size], start):
                question = str(row["question"]).strip()
                answers = row.get("golden_answers") or []
                answer = str(answers[0]).strip() if answers else ""
                if question and answer:
                    states.append({
                        "row_no": row_no, "row": row, "question": question,
                        "answers": answers, "answer": answer,
                        "messages": [{"role": "user", "content": (
                            "Answer the question using the search tool when needed. "
                            "Reason inside <think>...</think>. To search, emit exactly "
                            "<search>query</search>; after each search you will receive "
                            "<information>...</information>. Finish with exactly "
                            "<answer>final answer</answer>.\nQuestion: " + question
                        )}],
                        "turns": [], "searched": 0, "queries": [], "done": False,
                    })
            for _ in range(args.max_rounds):
                active = [s for s in states if not s["done"]]
                if not active:
                    break
                # Keep the question and the most recent tool exchange in the
                # context.  The full assistant trajectory is retained in
                # ``turns`` for SFT, while this bound prevents multi-round
                # passages from exceeding the 4096-token context window.
                for state in active:
                    if len(state["messages"]) > 3:
                        state["messages"] = [state["messages"][0]] + state["messages"][-2:]
                prompts = [tokenizer.apply_chat_template(s["messages"], tokenize=False, add_generation_prompt=True) for s in active]
                generated_batch = llm.generate(prompts, sampling)
                for state, request_output in zip(active, generated_batch):
                    generated = normalize_segment(request_output.outputs[0].text.strip())
                    state["turns"].append(generated)
                    if ANSWER_RE.search(generated):
                        state["done"] = True
                        continue
                    match = re.search(r"<search>\s*(.*?)\s*</search>", generated, re.I | re.S)
                    if not match:
                        state["done"] = True
                        continue
                    query = match.group(1).strip()
                    if not normalize(query):
                        state["invalid_reason"] = "empty search query"
                        state["done"] = True
                        continue
                    repeated_query = normalize(query) in {normalize(q) for q in state["queries"]}
                    if repeated_query:
                        state["invalid_reason"] = "repeated search query (no progress)"
                        state["done"] = True
                        continue
                    state["queries"].append(query)
                    hits = searcher.search(query, args.topk)
                    passages = []
                    for hit in hits:
                        content = hit_contents(hit)
                        passages.append(content[:1800])
                    if not passages:
                        state["invalid_reason"] = "empty information result (no progress)"
                        state["done"] = True
                        continue
                    state["searched"] += 1
                    state["messages"].append({"role": "assistant", "content": generated})
                    information = "<information>\n" + "\n\n".join(passages) + "\n</information>"
                    force_answer = state["searched"] >= args.max_searches
                    final_instruction = (
                        " This is the final allowed search; do not search again. Output the required answer tag now."
                        if force_answer else
                        " If the evidence answers the question, stop searching and output the required answer tag."
                    )
                    state["messages"].append({
                        "role": "user",
                        "content": information + "\nUse the evidence above." + final_instruction,
                    })
                    # Retain tool results in the serialized teacher trajectory
                    # as well as in the live prompt; otherwise the SFT record
                    # would contain a search call but no evidence turn.
                    state["turns"].append(information)
            for state in states:
                assistant = "\n".join(state["turns"])
                final = ANSWER_RE.findall(assistant)
                valid_answer = any(normalize(x) == normalize(str(a)) for x in final for a in state["answers"])
                valid_progress, _ = validate_tool_progress(assistant, is_valid_sequence)
                if debug:
                    debug.write(json.dumps({"question": state["question"], "gold": state["answers"], "assistant": assistant, "searched": state["searched"], "valid_answer": valid_answer}, ensure_ascii=False) + "\n")
                if state["searched"] and final and valid_answer and valid_progress and "<search>" in assistant and any("<information>" in m.get("content", "") for m in state["messages"]):
                    out.write(json.dumps({
                        "question": state["question"], "answer": state["answer"],
                        "assistant": assistant, "data_source": state["row"].get("data_source", "unknown"),
                        "teacher": "Qwen3.5-27B", "search_count": state["searched"],
                        "label_type": "teacher_bm25_validated", "row": state["row_no"],
                    }, ensure_ascii=False) + "\n")
                    written += 1
            out.flush()
            print(json.dumps({"seen": min(start + args.batch_size, len(rows)), "valid": written}), flush=True)
    if debug:
        debug.close()
    print(json.dumps({"seen": len(rows), "valid": written, "output": str(out_path)}))


if __name__ == "__main__":
    main()
